# Generated by Django 3.2.7 on 2021-10-04 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
