# Generated by Django 3.2.7 on 2021-10-05 19:43

import ad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_product_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.JSONField(default=ad.models.default_location),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default=2, max_length=13),
            preserve_default=False,
        ),
    ]
