# Generated by Django 3.2.7 on 2021-10-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
