# Generated by Django 3.2.7 on 2021-10-01 19:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
