# Generated by Django 3.2.7 on 2021-10-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comments_image'),
        ('blog', '0004_auto_20211001_1921'),
    ]

    operations = [
    ]
